## Basic Configuration
baseurl = "https://thsp.dev/"
languageCode = "en"

title = "My Tech Notes"
theme = "hyde-hyde"

## Hugo Built-in Features
disqusShortname = "thsp-dev"
googleAnalytics = "UA-160020317-1"
enableRobotsTXT = true

summarylength = 30

paginate = 10

## Site Settings
[params]
    author = "Thiago Pinto"
    title = "SRE"
    description = "Don't forget your towel"
    authorimage = "avatar.png"
    dateformat = "2006-01-02"

    # sidebar, copyright & license
    copyright = "htr3n"
    since = 2019
    license = "CC BY-SA 4.0"
    licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
    showBuiltWith = true

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"
    postNavigation = true
    relatedPosts = true

    # please choose either GraphComment or Disqus or Utterances
    #GraphCommentId = "..."
    #UtterancesRepo = "..." # https://utteranc.es/
    #UtterancesIssueTerm = "..." # pathname, url, title, og:title
    #UtterancesTheme = "..." # github-light or github-dark

    # Table of contents
    #toc = none, "hugo", or "tocbot"

## Social Accounts
[params.social]
    github = "thspinto"
    # instagram = "<username>"
    # xing = "<username>"
    linkedin = "thspinto"
    twitter = "thspinto"
    # facebook = "<username>"
    # stackoverflow = "<username>"
    # telegram = "<username>"
    # orcid = "<xxxx-xxxx-xxxx-xxxx>"
    # email = "your-email@example.com"
    # gravatar = "your-email@example.com"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
# [[menu.main]]
#     name = "Portfolio"
#     identifier = "portfolio"
#     weight = 200
#     url = "/portfolio/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"
